version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: bookify_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: bookify
      MYSQL_USER: bookify
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  php:
    image: php:8.1-fpm
    container_name: bookify_php
    working_dir: /var/www/backend
    volumes:
      - ./backend:/var/www/backend
      - ./backend/vendor:/var/www/backend/vendor
    depends_on:
      - db

  composer:
    image: composer:2
    container_name: bookify_composer
    working_dir: /var/www/backend
    volumes:
      - ./backend:/var/www/backend

  node:
    image: node:18
    container_name: bookify_node
    working_dir: /var/www/frontend
    volumes:
      - ./frontend:/var/www/frontend
    command: ["tail", "-f", "/dev/null"]

  nginx:
    image: nginx:alpine
    container_name: bookify_nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/backend
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: bookify_pma
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
